import * as esbuild from 'esbuild';
import { existsSync, mkdirSync, copyFileSync, readdirSync, writeFileSync } from 'fs';
import { spawnSync } from 'child_process';

const dev = process.argv.includes('--dev');
const port = Number(process.env.PORT ?? 3000);

// ── libav.js WASM artifacts ───────────────────────────────────────────────
// Build both libav.js WASM variants on first use if either is missing.
// The vendor/ directory is gitignored; this runs automatically after clone.
const HEVC_WASM = 'vendor/libav-hevc/libav-6.8.8.0-hevc-aac.wasm.wasm';
const AVC_WASM  = 'vendor/libav-avc-av1/libav-6.8.8.0-avc-av1.wasm.wasm';
if (!existsSync(HEVC_WASM) || !existsSync(AVC_WASM)) {
  console.log('WASM artifacts missing — running build:wasm (requires Docker)…');
  const result = spawnSync(process.execPath, ['scripts/build-wasm.mjs'], { stdio: 'inherit' });
  if (result.status !== 0) {
    console.error('build:wasm failed. Build aborted.');
    process.exit(result.status ?? 1);
  }
}

// ── onnxruntime-web WASM artifacts ───────────────────────────────────────────
// Copy ort WASM files into dist/ort/ so the browser can fetch them.
function copyOrtWasm() {
  const src = 'node_modules/onnxruntime-web/dist';
  const dst = 'dist/ort';
  mkdirSync(dst, { recursive: true });
  for (const f of readdirSync(src)) {
    // Copy WASM binaries and their JS/MJS loader wrappers (needed for dynamic imports at runtime).
    if (f.endsWith('.wasm') || (f.startsWith('ort-') && f.endsWith('.mjs'))) {
      copyFileSync(`${src}/${f}`, `${dst}/${f}`);
    }
  }
}
copyOrtWasm();

// ── Service worker ────────────────────────────────────────────────────────────
// Generate sw.js with a baked-in cache version so each build invalidates the
// previous cache. The SW is served from / so it controls the whole origin.
function generateServiceWorker() {
  const version = new Date().toISOString().slice(0, 19).replace(/[-:T]/g, ''); // e.g. 20260117142359
  const sw = `// Auto-generated by build.mjs — do not edit.
const CACHE = 'blurweb-${version}';

// Precache the core app shell so the UI loads offline.
const PRECACHE = ['/', '/src/style.css', '/dist/bundle.js', '/dist/hevcWorker.js'];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)));
  self.skipWaiting();
});

// Remove old caches from previous versions.
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

// Cache-first for same-origin GET requests (models, WASM, assets).
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
  e.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const hit = await cache.match(e.request);
      if (hit) return hit;
      const res = await fetch(e.request);
      if (res.ok) cache.put(e.request, res.clone());
      return res;
    })
  );
});
`;
  writeFileSync('sw.js', sw);
}
generateServiceWorker();

const buildConfig = {
  entryPoints: {
    bundle: 'src/main.ts',
    hevcWorker: 'src/hevcWorker.ts',
  },
  bundle: true,
  outdir: 'dist',
  format: 'esm',
  sourcemap: dev,
  target: ['chrome114', 'firefox115'],
  minify: !dev,
};

if (dev) {
  const ctx = await esbuild.context(buildConfig);
  await ctx.watch();
  const { port: actualPort } = await ctx.serve({
    servedir: '.',
    port,
  });
  console.log(`Dev server: http://localhost:${actualPort}`);
  console.log('Press Ctrl+C to stop.');
} else {
  await esbuild.build(buildConfig);
  console.log('Build complete → dist/bundle.js + dist/hevcWorker.js');
}
